# Generated by Django 2.1.3 on 2019-01-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190120_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='player',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
