# Generated by Django 2.1.3 on 2019-01-20 15:32

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tourn_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 21, 15, 32, 22, 468776, tzinfo=utc)),
        ),
    ]
