# Generated by Django 2.1.3 on 2019-01-20 15:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20190120_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tourn_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 21, 15, 34, 33, 340254, tzinfo=utc)),
        ),
    ]
