# Generated by Django 2.1.3 on 2019-01-20 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='date_joined',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
