# Generated by Django 2.1.3 on 2019-01-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0002_auto_20190120_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='handicap',
            field=models.IntegerField(null=True),
        ),
    ]
